RentACar/Controllers/ReservasController.cs
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using RentACar_Modelos;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;

namespace RentACar.Controllers
{
    public class ReservasController : Controller
    {
        string urlBase = "https://localhost:44317";

        // GET: Reservas
        public async Task<ActionResult> Index()
        {
            this.ViewData["ResultadosEnPantalla"] = "Activas";

            using (var httpCliente = new HttpClient())
            {
                httpCliente.BaseAddress = new Uri(urlBase);
                HttpResponseMessage respuesta = await httpCliente.GetAsync("api/reservas");

                if (respuesta.IsSuccessStatusCode)
                {
                    string resultado = respuesta.Content.ReadAsStringAsync().Result;
                    List<Reserva> listaReservas = JsonConvert.DeserializeObject<List<Reserva>>(resultado);

                    return this.View(listaReservas);
                }
            }
            return View();
        }

        public ActionResult Crear()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Crear(Reserva reserva)
        {
            using (var clienteHttp = new HttpClient())
            {
                try
                {
                    clienteHttp.BaseAddress = new Uri(urlBase);
                    HttpResponseMessage respuesta = await clienteHttp.PostAsync("api/reservas", new StringContent(
                        new JavaScriptSerializer().Serialize(reserva), Encoding.UTF8, "application/json"));

                    // si algo sale mal con la peticion
                    if (respuesta.StatusCode == System.Net.HttpStatusCode.BadRequest)
                    {
                        JObject contenidoRespuesta = JObject.Parse(await respuesta.Content.ReadAsStringAsync());
                        string mensajeApi = contenidoRespuesta.GetValue("Message").ToString();

                        this.ViewData["MensajeError"] = mensajeApi;
                        return this.View();
                    }
                    else if (respuesta.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        this.ViewData["MensajeExito"] = await respuesta.Content.ReadAsStringAsync();
                    }
                    else if (respuesta.StatusCode == System.Net.HttpStatusCode.InternalServerError)
                    {
                        this.ViewData["MensajeError"] = "Error de lado de servidor.";
                    }
                }
                catch (Exception)
                {
                    throw;
                }
            }

            return this.View();
        }

        public async Task<ActionResult> VerFinalizadas()
        {
            this.ViewData["ResultadosEnPantalla"] = "Inactivas";

            using (var clientHttp = new HttpClient())
            {
                clientHttp.BaseAddress = new Uri(urlBase);
                var respuesta = await clientHttp.GetAsync("api/reservasFinalizadas");

                if (respuesta.IsSuccessStatusCode)
                {
                    string resultado = await respuesta.Content.ReadAsStringAsync();
                    List<Reserva> listaReservas = JsonConvert.DeserializeObject<List<Reserva>>(resultado);
                    return this.View("Index", listaReservas);
                }
            }

            return this.View("Index");
        }

        [HttpGet]
        public async Task<ActionResult> ActualizarEstado(int? idReserva)
        {
            if (idReserva is null)
            {
                this.ViewData["MensajeError"] = "Por favor, proveer el ID de la reserva.";
                return this.View();
            }

            using (var clienteHttp = new HttpClient())
            {
                clienteHttp.BaseAddress = new Uri(urlBase);
                HttpResponseMessage respuesta = await clienteHttp.GetAsync($"api/reservas/{idReserva}");

                if (respuesta.IsSuccessStatusCode)
                {
                    string resultado = await respuesta.Content.ReadAsStringAsync();
                    Reserva reservaEncontrada = JsonConvert.DeserializeObject<Reserva>(resultado);

                    this.Session["IdReserva"] = reservaEncontrada.Id;
                    return this.View(reservaEncontrada);
                }

                JObject contenidoRespuesta = JObject.Parse(await respuesta.Content.ReadAsStringAsync());
                string mensajeApi = contenidoRespuesta.GetValue("Message").ToString();
                this.ViewData["MensajeError"] = mensajeApi;
            }

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> ActualizarEstado([Bind(Exclude = "Id")]Reserva reserva)
        {
            using (var clienteHttp = new HttpClient())
            {
                clienteHttp.BaseAddress = new Uri(urlBase);
                HttpResponseMessage respuesta = await clienteHttp.PutAsync($"api/reservas/{this.Session["IdReserva"]}/{reserva.EsActiva}", new StringContent(
                    new JavaScriptSerializer().Serialize(reserva), Encoding.UTF8, "application/json"));

                // si algo sale mal con la peticion
                if (respuesta.StatusCode == System.Net.HttpStatusCode.BadRequest)
                {
                    JObject contenidoRespuesta = JObject.Parse(await respuesta.Content.ReadAsStringAsync());
                    string mensajeApi = contenidoRespuesta.GetValue("Message").ToString();

                    this.ViewData["MensajeError"] = mensajeApi;
                    return this.View();
                }
                else if (respuesta.StatusCode == System.Net.HttpStatusCode.OK)
                {
                    this.ViewData["MensajeExito"] = await respuesta.Content.ReadAsStringAsync();
                }
                else if (respuesta.StatusCode == System.Net.HttpStatusCode.InternalServerError)
                {
                    this.ViewData["MensajeError"] = "Error de lado de servidor.";
                }
            }

            return this.View();
        }
    }
}

RentACar/Views/Reservas/ActualizarEstado.cshtml
@using RentACar_Modelos
@model Reserva
@{
    ViewBag.Title = "Anular";
}

@if (ViewData.ContainsKey("MensajeError"))
{
    <h4 class="alert alert-danger">@ViewData["MensajeError"]</h4>
}
else if (ViewData.ContainsKey("MensajeExito"))
{
    <h4 class="alert alert-success">@ViewData["MensajeExito"]</h4>
}
else
{
    <h2>Anular Reserva</h2>
    <h3>En caso de devolución cambiar estado de "EsActiva" a 0</h3>
    @Html.ActionLink("Regresar", "Index", null, new { @class = "btn btn-primary" })
    using (Html.BeginForm("ActualizarEstado", "Reservas", FormMethod.Post))
    {
        <div>@Html.AntiForgeryToken()</div>

        <div class="form-group">
            @Html.LabelFor(r => r.Matricula)
            @Html.EditorFor(r => r.Matricula, new { htmlAttributes = new { @class = "form-control", @disabled = "disabled" } })
        </div>

        <div class="form-group">
            @Html.LabelFor(r => r.IdCliente)
            @Html.EditorFor(r => r.IdCliente, new { htmlAttributes = new { @class = "form-control", @type = "number", @min = "0", @disabled = "disabled" } })
        </div>

        <div class="form-group">
            @Html.LabelFor(r => r.FechaInicio)
            @Html.TextBoxFor(r => r.FechaInicio, new { @class = "form-control datepicker", @disabled = "disabled" })
        </div>

        <div class="form-group">
            @Html.LabelFor(r => r.FechaFin)
            @Html.TextBoxFor(r => r.FechaFin, new { @class = "form-control datepicker", @disabled = "disabled" })
        </div>

        <div class="form-group">
            @Html.LabelFor(r => r.EsActiva)
            @Html.EditorFor(r => r.EsActiva, new { htmlAttributes = new { @class = "form-control", @type = "number", @min = "0" } })
        </div>

        <input type="submit" class="btn btn-primary" value="Actualizar" />
    }
}

RentACar/Views/Reservas/Anular.cshtml
@using RentACar_Modelos
@model Reserva
@{
    ViewBag.Title = "Editar";
}

@if (ViewData.ContainsKey("MensajeError"))
{
    <h4 class="alert alert-danger">@ViewData["MensajeError"]</h4>
}
else if (ViewData.ContainsKey("MensajeExito"))
{
    <h4 class="alert alert-success">@ViewData["MensajeExito"]</h4>
}
else
{
    <h2>Anular Reserva</h2>
    <h3>En caso de devolución cambiar estado de "EsActiva" a 0</h3>
    using (Html.BeginForm("Editar", "Reservas", FormMethod.Post))
    {
        <div>@Html.AntiForgeryToken()</div>

        <div class="form-group">
            @Html.LabelFor(r => r.Matricula)
            @Html.EditorFor(r => r.Matricula, new { htmlAttributes = new { @class = "form-control", @disabled = "disabled" } })
        </div>

        <div class="form-group">
            @Html.LabelFor(r => r.IdCliente)
            @Html.EditorFor(r => r.IdCliente, new { htmlAttributes = new { @class = "form-control", @type = "number", @min = "0", @disabled = "disabled" } })
        </div>

        <div class="form-group">
            @Html.LabelFor(r => r.FechaInicio)
            @Html.TextBoxFor(r => r.FechaInicio, new { @class = "form-control datepicker", @disabled = "disabled" })
        </div>

        <div class="form-group">
            @Html.LabelFor(r => r.FechaFin)
            @Html.TextBoxFor(r => r.FechaFin, new { @class = "form-control datepicker", @disabled = "disabled" })
        </div>

        <div class="form-group">
            @Html.LabelFor(r => r.EsActiva)
            @Html.EditorFor(r => r.EsActiva, new { htmlAttributes = new { @class = "form-control", @type = "number", @min = "0" } })
        </div>

        <input type="submit" class="btn btn-primary" value="Actualizar" />
    }
}

RentACar/Views/Reservas/BitacoraReservas.cshtml
@using RentACar_Modelos
@model IEnumerable<Reserva>
@{
    ViewBag.Title = "BitacoraReservas";
}

<h2>Bitacora de Reservas</h2>

@if (Model is null)
{
    <h4 class="alert alert-warning">@this.ViewData["MensajeError"]</h4>
}
else
{
    <table class="table">
        <thead>
            <tr>
                <th scope="col">Nombre de Cliente</th>
                <th scope="col">Matricula de Coche</th>
                <th scope="col">Precio de Alquiler</th>
                <th scope="col">Dias de Alquiler</th>
                <th scope="col">Fecha Inicio</th>
                <th scope="col">Fecha Final</th>
                <th scope="col">Precio Total</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var reserva in Model)
            {
                <tr>
                    <td scope="row">@reserva.NombreCliente</td>
                    <td scope="row">@reserva.Matricula</td>
                    <td scope="row">@reserva.PrecioAlquilerCoche</td>
                    <td scope="row">@reserva.DiasAlquiler</td>
                    <td scope="row">@reserva.FechaInicio.ToShortDateString()</td>
                    <td scope="row">@reserva.FechaFin.ToShortDateString()</td>
                    <td scope="row">@reserva.PrecioTotal</td>
                </tr>
            }
        </tbody>
    </table>
}

RentACar/Views/Reservas/Crear.cshtml
@using RentACar_Modelos
@model Reserva
@{
    ViewBag.Title = "Crear";
}

@if (this.ViewData.ContainsKey("MensajeError"))
{
    <h4 class="alert alert-danger">@this.ViewData["MensajeError"]</h4>
    @Html.ActionLink("Regresar", "Index", null, new { @class = "btn btn-primary" })
}

@if (this.ViewData.ContainsKey("MensajeExito"))
{
    <h4 class="alert alert-success">@this.ViewData["MensajeExito"]</h4>
    @Html.ActionLink("Regresar", "Index", null, new { @class = "btn btn-primary" })
}

@if (!this.ViewData.ContainsKey("MensajeError")
    && !this.ViewData.ContainsKey("MensajeExito"))
{
    <h2>Nueva reserva</h2>

    using (Html.BeginForm("Crear", "Reservas", FormMethod.Post))
    {
        <div>@Html.AntiForgeryToken()</div>
        <div class="form-group">
            @Html.LabelFor(r => r.Matricula)
            @Html.EditorFor(r => r.Matricula, new { htmlAttributes = new { @class = "form-control" } })
        </div>

        <div class="form-group">
            @Html.LabelFor(r => r.IdCliente)
            @Html.EditorFor(r => r.IdCliente, new { htmlAttributes = new { @class = "form-control", @type = "number", @min = "0" } })
        </div>

        <div class="form-group">
            @Html.LabelFor(r => r.IdVendedor)
            @Html.EditorFor(r => r.IdVendedor, new { htmlAttributes = new { @class = "form-control", @type = "number", @min = "0" } })
        </div>

        <div class="form-group">
            @Html.LabelFor(r => r.FechaInicio)
            @Html.TextBoxFor(r => r.FechaInicio, new { @type = "date", @class = "form-control datepicker" })
        </div>

        <div class="form-group">
            @Html.LabelFor(r => r.FechaFin)
            @Html.TextBoxFor(r => r.FechaFin, new { @type = "date", @class = "form-control datepicker" })
        </div>

        <input type="submit" class="btn btn-primary" value="Crear reserva" />
    }
}

RentACar/Views/Reservas/Index.cshtml
@using RentACar_Modelos
@model IEnumerable<Reserva>
@{
    ViewBag.Title = "Reservas";
}

<h2>Todas las reservas</h2>
@Html.ActionLink("Agregar reserva", "Crear", null, new { @class = "btn btn-primary" })

@if (this.ViewData["ResultadosEnPantalla"].ToString() == "Inactivas")
{
    @Html.ActionLink("Ver Activas", "Index", null, new { @class = "btn btn-success" })
}
else if (this.ViewData["ResultadosEnPantalla"].ToString() == "Activas")
{
    @Html.ActionLink("Ver Inactivas", "VerFinalizadas", null, new { @class = "btn btn-danger" })
}

@if (Model is null)
{
    <h4 class="alert alert-warning">@this.ViewData["MensajeError"]</h4>
}
else
{
    <table class="table">
        <thead>
            <tr>
                <th scope="col">Nombre de Cliente</th>
                <th scope="col">Matricula de Coche</th>
                <th scope="col">Precio de Alquiler</th>
                <th scope="col">Dias de Alquiler</th>
                <th scope="col">Fecha Inicio</th>
                <th scope="col">Fecha Final</th>
                <th scope="col">Precio Total</th>
                <th scope="col">Id de Vendedor</th>
                <th scope="col">Nombre de Vendedor</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var reserva in Model)
            {
                <tr>
                    <td scope="row">@reserva.NombreCliente</td>
                    <td scope="row">@reserva.Matricula</td>
                    <td scope="row">@reserva.PrecioAlquilerCoche</td>
                    <td scope="row">@reserva.DiasAlquiler</td>
                    <td scope="row">@reserva.FechaInicio.ToShortDateString()</td>
                    <td scope="row">@reserva.FechaFin.ToShortDateString()</td>
                    <td scope="row">@reserva.PrecioTotal</td>
                    <td scope="row">@reserva.IdVendedor</td>
                    <td scope="row">@reserva.NombreVendedor</td>
                    <td>
                        @Html.ActionLink("Modificar Estado", "ActualizarEstado", new { idReserva = reserva.Id }, new { @class = "btn btn-warning" })
                    </td>
                </tr>
            }
        </tbody>
    </table>
}