RentACar/Controllers/CochesController.cs
using Newtonsoft.Json;
using RentACar.Models;
using RentACar_Modelos;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;

namespace RentACar.Controllers
{
    public class CochesController : Controller
    {
        string urlBase = "https://localhost:44317";

        ////private readonly HttpClient _httpClient = new HttpClient()
        ////{
        ////    BaseAddress = new Uri("https://localhost:44317")
        ////};

        /// <summary>
        /// Consume endpoint para obtener todos los clientes y los envia a la vista
        /// </summary>
        /// <returns>Una vista</returns>
        public async Task<ActionResult> Index()
        {
            this.ViewData["TextoBotonResultados"] = "Disponibles";

            using (var clienteHttp = new HttpClient())
            {
                clienteHttp.BaseAddress = new Uri(urlBase);
                ////clienteHttp.DefaultRequestHeaders.Accept.Clear();
                ////clienteHttp.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

                HttpResponseMessage respuesta = await clienteHttp.GetAsync("api/coches");

                if (respuesta.IsSuccessStatusCode)
                {
                    string resultado = respuesta.Content.ReadAsStringAsync().Result;
                    List<Coche> listaCoches = JsonConvert.DeserializeObject<List<Coche>>(resultado);

                    return this.View(listaCoches);
                }
            }

            return this.View();
        }

        private async Task<CocheViewModel> llenarModelo(CocheViewModel modelo = null)
        {
            var marcas = await GetSelectMarcas();
            var colores = await GetSelectColores();
            var garajes = await GetSelectGarajes();

            if (modelo is null)
            {
                modelo = new CocheViewModel()
                {
                    SelectMarcas = marcas.ToList(),
                    SelectColores = colores.ToList(),
                    SelectGarajes = garajes.ToList()
                };

                return modelo;
            }

            modelo.SelectMarcas = marcas.ToList();
            modelo.SelectColores = colores.ToList();
            modelo.SelectGarajes = garajes.ToList();

            return modelo;
        }

        /// <summary>
        /// Consulta los detalles para crear un nuevo coche
        /// </summary>
        /// <returns>Vista para crear un nuevo coche</returns>
        [HttpGet]
        public async Task<ActionResult> Crear()
        {
            return this.View(await llenarModelo());
        }

        /// <summary>
        /// Graba los datos de un nuevo coche en la base de datos
        /// </summary>
        /// <param name="coche">Objeto con los datos del nuevo coche</param>
        /// <returns>Redireccion a la vista Index</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Crear(CocheViewModel modeloCoche)
        {
            if (!ModelState.IsValid)
            {
                return this.View(await llenarModelo(modeloCoche));
            }

            using (var clienteHttp = new HttpClient())
            {
                clienteHttp.BaseAddress = new Uri(urlBase);
                HttpResponseMessage respuesta = await clienteHttp.PostAsync("api/coches", new StringContent(
                    new JavaScriptSerializer().Serialize(modeloCoche.Coche), Encoding.UTF8, "application/json"));

                if (respuesta.IsSuccessStatusCode)
                {
                    ModelState.Clear();
                    return this.RedirectToAction("Index");
                }
                else
                {
                    this.ViewData["MensajeError"] = "Error al crear el coche";
                }
            }
            return this.RedirectToAction("Index");
        }

        public async Task<IEnumerable<Marca>> GetSelectMarcas()
        {
            using (var clienteHttp = new HttpClient())
            {
                clienteHttp.BaseAddress = new Uri(urlBase);
                HttpResponseMessage respuesta = await clienteHttp.GetAsync("api/marcas");

                if (respuesta.IsSuccessStatusCode)
                {
                    string resultado = respuesta.Content.ReadAsStringAsync().Result;
                    List<Marca> listaMarcas = JsonConvert.DeserializeObject<List<Marca>>(resultado);
                    return listaMarcas;
                }
            }

            return null;
        }

        public async Task<IEnumerable<ColorCoche>> GetSelectColores()
        {
            using (var clienteHttp = new HttpClient())
            {
                clienteHttp.BaseAddress = new Uri(urlBase);
                HttpResponseMessage respuesta = await clienteHttp.GetAsync("api/coloresCoche");

                if (respuesta.IsSuccessStatusCode)
                {
                    string resultado = respuesta.Content.ReadAsStringAsync().Result;
                    List<ColorCoche> listaColores = JsonConvert.DeserializeObject<List<ColorCoche>>(resultado);
                    return listaColores;
                }
            }

            return null;
        }

        public async Task<IEnumerable<Garaje>> GetSelectGarajes()
        {
            using (var clienteHttp = new HttpClient())
            {
                clienteHttp.BaseAddress = new Uri(urlBase);
                HttpResponseMessage respuesta = await clienteHttp.GetAsync("api/garajes");

                if (respuesta.IsSuccessStatusCode)
                {
                    string resultado = respuesta.Content.ReadAsStringAsync().Result;
                    List<Garaje> listaGarajes = JsonConvert.DeserializeObject<List<Garaje>>(resultado);
                    return listaGarajes;
                }
            }

            return null;
        }

        public async Task<ActionResult> ConsultarListaDisponibles()
        {
            this.ViewData["TextoBotonResultados"] = "Todos";

            using (var clientHttp = new HttpClient())
            {
                clientHttp.BaseAddress = new Uri(urlBase);
                var respuesta = await clientHttp.GetAsync("api/cochesDisponibles");

                if (respuesta.IsSuccessStatusCode)
                {
                    string resultado = await respuesta.Content.ReadAsStringAsync();
                    List<Coche> listaCoches = JsonConvert.DeserializeObject<List<Coche>>(resultado);
                    return this.View("Index", listaCoches);
                }
            }

            return this.View("Index");
        }

        ////[HttpGet]
        ////public async Task<ActionResult> ConsultarPorFiltro(int idFiltro)
        ////{
        ////    using (var clienteHttp = new HttpClient())
        ////    {
        ////        clienteHttp.BaseAddress = new Uri(urlBase);
        ////        HttpResponseMessage respuesta = await clienteHttp.GetAsync($"api/coches/{idFiltro}");

        ////        if (respuesta.IsSuccessStatusCode)
        ////        {

        ////        }
        ////    }
        ////}
    }
}

RentACar/Views/Coches/Crear.cshtml
@using RentACar.Models
@model CocheViewModel
@{
    ViewBag.Title = "Crear";
    //IEnumerable<Marca> listaMarcas = this.ViewData["listaMarcas"] as IEnumerable<Marca>;
    //IEnumerable<ColorCoche> listaColores = this.ViewData["listaColores"] as IEnumerable<ColorCoche>;
    //IEnumerable<Garaje> listaGarajes = this.ViewData["listaGarajes"] as IEnumerable<Garaje>;
}

<h2>Crear Coche</h2>
@Html.ActionLink("Regresar", "Index", null, new { @class = "btn btn-info" })

@using (Html.BeginForm("Crear", "Coches", FormMethod.Post))
{
    @*@Html.HiddenFor(x => x.SelectMarcas)
        @Html.HiddenFor(x => x.SelectColores)
        @Html.HiddenFor(x => x.SelectGarajes)*@

    <div>@Html.AntiForgeryToken()</div>

    <div class="form-group">
        @Html.LabelFor(c => c.Coche.Matricula)
        @Html.EditorFor(c => c.Coche.Matricula, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(c => c.Coche.Matricula, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        @Html.Label("Precio de Alquiler")
        @Html.EditorFor(c => c.Coche.PrecioAlquiler, new { htmlAttributes = new { @class = "form-control", @type = "number", @min = "0" } })
        @Html.ValidationMessageFor(c => c.Coche.PrecioAlquiler, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        @Html.LabelFor(c => c.SelectMarcas)
        @Html.DropDownListFor(c => c.Coche.IdMarca,
                    new SelectList(Model.SelectMarcas, "IdMarca", "Nombre", Model.SelectMarcas.First().IdMarca),
                    new { @class = "form-control" })
    </div>

    <div class="form-group">
        @Html.LabelFor(c => c.SelectColores)
        @Html.DropDownListFor(c => c.Coche.Color,
                    new SelectList(Model.SelectColores, "IdColor", "Color", Model.SelectColores.First().IdColor),
                    new { @class = "form-control" })
    </div>

    <div class="form-group">
        @Html.LabelFor(c => c.SelectGarajes)
        @Html.DropDownListFor(c => c.Coche.Garaje,
                    new SelectList(Model.SelectGarajes, "IdGaraje", "Direccion", Model.SelectGarajes.First().IdGaraje),
                    new { @class = "form-control" })
    </div>

    @*<div class="form-group">
            @Html.LabelFor(c => c.Marca)
            @Html.DropDownListFor(c => c.IdMarca,
                        new SelectList(listaMarcas, "IdMarca", "Nombre", listaMarcas.First().IdMarca),
                        new { @class = "form-control" })
        </div>

        <div class="form-group">
            @Html.LabelFor(c => c.Color)
            @Html.DropDownListFor(c => c.IdColor,
                        new SelectList(listaColores, "IdColor", "Color", listaColores.First().IdColor),
                        new { @class = "form-control" })
        </div>

        <div class="form-group">
            @Html.LabelFor(c => c.Garaje)
            @Html.DropDownListFor(c => c.IdGaraje,
                        new SelectList(listaGarajes, "IdGaraje", "Direccion", listaGarajes.First().IdGaraje),
                        new { @class = "form-control" })
        </div>*@

    <input type="submit" class="btn btn-success" value="Crear" />
}

RentACar/Views/Coches/Index.cshtml
@using RentACar_Modelos
@model IEnumerable<Coche>

<h1>Coches</h1>
@*@Html.ActionLink("Nuevo Coche", "Crear", null, new { @class = "btn btn-primary" })

@if (this.ViewData["TextoBotonResultados"].ToString() == "Disponibles")
{
    @Html.ActionLink(this.ViewData["TextoBotonResultados"].ToString(), "ConsultarListaDisponibles", null, new { @class = "btn btn-warning" })
}
else if (this.ViewData["TextoBotonResultados"].ToString() == "Todos")
{
    @Html.ActionLink(this.ViewData["TextoBotonResultados"].ToString(), "Index", null, new { @class = "btn btn-warning" })
}*@

@if (Model != null)
{
    <table class="table">
        <thead>
            <tr>
                <th scope="col">Matricula</th>
                <th scope="col">Color</th>
                <th scope="col">Precio de Alquiler</th>
                <th scope="col">Garaje</th>
                <th scope="col">Marca</th>
            </tr>
        </thead>
        <tbody>
            @foreach (Coche coche in Model)
            {
                <tr>
                    <td scope="row">@coche.Matricula</td>
                    <td>@coche.Color</td>
                    <td>@coche.PrecioAlquiler</td>
                    <td>@coche.Garaje</td>
                    <td>@coche.Marca</td>
                    <td>
                        @Html.ActionLink("Editar", "Editar", null, new { @class = "btn btn-warning" })
                        @Html.ActionLink("Eliminar", "Eliminar", null, new { @class = "btn btn-danger" })
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <h3>No hay datos disponibles.</h3>
}